Repository NOW-SOPT-CDSP-WEB6/Naver-Reservation-BE, pull requests merged in 2024-05, with the labels that each got.

#4 프로젝트 기본 설정을 진행합니다.
  console.sql.html
  src/main/java/sopt/seminar/sopt/common/baseEntity/BaseEntity.java
  src/main/java/sopt/seminar/sopt/common/config/JpaAuditingConfig.java
  src/main/java/sopt/seminar/sopt/common/dto/ErrorResponse.java
  src/main/java/sopt/seminar/sopt/common/dto/SuccessMessage.java
  src/main/java/sopt/seminar/sopt/common/dto/response/statusEnum/SuccessStatus.java
  src/main/java/sopt/seminar/sopt/common/exception/BusinessException.java
  src/main/java/sopt/seminar/sopt/common/exception/GlobalExceptionHandler.java
  src/main/java/sopt/seminar/sopt/common/exception/NotFoundException.java
  src/main/java/sopt/seminar/sopt/common/exception/errorStatusEnum/ErrorMessage.java
  src/main/java/sopt/seminar/sopt/member/entity/Member.java
  src/main/java/sopt/seminar/sopt/reservation/entity/Reservation.java
  src/main/java/sopt/seminar/sopt/store/entity/Store.java
Labels: feature

#6 1번,5번 API를 구현합니다.
  src/main/java/sopt/seminar/sopt/common/baseEntity/BaseEntity.java
  src/main/java/sopt/seminar/sopt/common/dto/SuccessMessage.java
  src/main/java/sopt/seminar/sopt/common/exception/errorStatusEnum/ErrorMessage.java
  src/main/java/sopt/seminar/sopt/member/exception/exceptionEnum/MemberNotFoundException.java
  src/main/java/sopt/seminar/sopt/member/repository/MemberJpaRepository.java
  src/main/java/sopt/seminar/sopt/member/service/MemberQueryService.java
  src/main/java/sopt/seminar/sopt/reservation/controller/ReservationReadController.java
  src/main/java/sopt/seminar/sopt/reservation/dto/response/ReservationCategorizedResponse.java
  src/main/java/sopt/seminar/sopt/reservation/entity/Category.java
  src/main/java/sopt/seminar/sopt/reservation/repository/ReservationJpaRepository.java
  src/main/java/sopt/seminar/sopt/reservation/service/ReservationQueryService.java
  src/main/java/sopt/seminar/sopt/store/controller/ReviewQueryController.java
  src/main/java/sopt/seminar/sopt/store/dto/response/ReviewResponse.java
  src/main/java/sopt/seminar/sopt/store/dto/response/ReviewSummaryResponse.java
  src/main/java/sopt/seminar/sopt/store/repository/StoreJpaRepository.java
  src/main/java/sopt/seminar/sopt/store/service/ReviewQueryService.java
Labels: feature

#8 Feat/#3 API NO.2,3,4 개발
  git
  src/main/java/sopt/seminar/sopt/common/dto/response/statusEnum/SuccessStatus.java
  src/main/java/sopt/seminar/sopt/common/exception/NotFoundException.java
  src/main/java/sopt/seminar/sopt/common/exception/errorStatusEnum/ErrorMessage.java
  src/main/java/sopt/seminar/sopt/member/entity/Member.java
  src/main/java/sopt/seminar/sopt/reservation/controller/ReservationCountPriceController.java
  src/main/java/sopt/seminar/sopt/reservation/controller/ReservationPostReviewController.java
  src/main/java/sopt/seminar/sopt/reservation/controller/ReservationReadController.java
  src/main/java/sopt/seminar/sopt/reservation/controller/ReservationStarController.java
  src/main/java/sopt/seminar/sopt/reservation/entity/Reservation.java
  src/main/java/sopt/seminar/sopt/reservation/repository/ReservationJpaRepository.java
  src/main/java/sopt/seminar/sopt/reservation/service/PostReviewDTO.java
  src/main/java/sopt/seminar/sopt/reservation/service/ReservationCountPriceService.java
  src/main/java/sopt/seminar/sopt/reservation/service/ReservationPostReviewService.java
  src/main/java/sopt/seminar/sopt/reservation/service/ReservationStarService.java
  src/main/resources/application.yml
Labels: feature

#10 요구사항 변경에 따른 리팩토링을 진행합니다.
  src/main/java/sopt/seminar/sopt/reservation/controller/ReservationCountPriceController.java
  src/main/java/sopt/seminar/sopt/reservation/controller/ReservationPostReviewController.java
  src/main/java/sopt/seminar/sopt/reservation/controller/ReservationStarController.java
  src/main/java/sopt/seminar/sopt/reservation/dto/request/PostReviewRequest.java
  src/main/java/sopt/seminar/sopt/reservation/entity/Category.java
  src/main/java/sopt/seminar/sopt/reservation/service/PostReviewDTO.java
  src/main/java/sopt/seminar/sopt/reservation/service/ReservationPostReviewService.java
  src/main/java/sopt/seminar/sopt/reservation/service/ReservationQueryService.java
Labels: refactor

#11 카테고리별 예약 반환 코드를 수정합니다.
  src/main/java/sopt/seminar/sopt/reservation/service/ReservationQueryService.java
Labels: refactor

#12 리뷰 미존재시 에러를 도출하도록 수정합니다.
  src/main/java/sopt/seminar/sopt/common/exception/errorStatusEnum/ErrorMessage.java
  src/main/java/sopt/seminar/sopt/store/service/ReviewQueryService.java
Labels: refactor

#13 CORS 설정을 진행합니다.
  src/main/java/sopt/seminar/sopt/common/config/WebConfig.java
  src/main/java/sopt/seminar/sopt/store/controller/ReviewQueryController.java
  src/main/java/sopt/seminar/sopt/store/service/ReviewQueryService.java
Labels: fix

#14 1번 API 응답값을 변경합니다.
  src/main/java/sopt/seminar/sopt/reservation/dto/response/ReservationCategorizedResponse.java
  src/main/java/sopt/seminar/sopt/reservation/service/ReservationQueryService.java
Labels: refactor

#15 1번 API 카테고리 반환 타입 한글로 변경
  src/main/java/sopt/seminar/sopt/common/config/WebConfig.java
  src/main/java/sopt/seminar/sopt/reservation/entity/Category.java
  src/main/java/sopt/seminar/sopt/reservation/entity/Reservation.java
  src/main/java/sopt/seminar/sopt/reservation/service/ReservationQueryService.java
Labels: refactor

#16 카테고리 관련 서비스 로직 변경을 진행합니다.
  src/main/java/sopt/seminar/sopt/common/exception/errorStatusEnum/ErrorMessage.java
  src/main/java/sopt/seminar/sopt/reservation/controller/ReservationCountPriceController.java
  src/main/java/sopt/seminar/sopt/reservation/repository/ReservationJpaRepository.java
  src/main/java/sopt/seminar/sopt/reservation/service/ReservationCountPriceService.java
Labels: fix

#17 리뷰 반환 시 리뷰 ID를 추가하여 반환합니다.
  src/main/java/sopt/seminar/sopt/store/dto/response/ReviewResponse.java
  src/main/java/sopt/seminar/sopt/store/service/ReviewQueryService.java
Labels: refactor
